config/routes.rb
Krasivo::Application.routes.draw do

  mount RedactorRails::Engine => '/redactor_rails'

  match 'subscriptions/subscribe' => 'subscriptions#subscribe'

  namespace :b2b do
    match 'food' => 'b2b#food'
    match 'portfolio' => 'b2b#portfolio'
    match 'catering' => 'b2b#catering'
    match 'price' => 'b2b#price'
    match 'contacts' => 'b2b#contacts'
  end
  match 'orders/refresh_captcha_div' => 'orders#refresh_captcha_div'
  resources :line_items
  resources :events
  resources :carts
  match 'appointments/refresh_captcha_div' => 'appointments#refresh_captcha_div'
  resources :appointments
  resources :recipes
  resources :orders

  devise_for :users, :controllers => { sessions: 'sessions' }

  # Vacancies
  match 'vacancies/:id' => 'vacancies#show', :as => :vacancy
  match 'vacancy' => 'vacancies#index', :as => :vacancies
  
  # Courses
  resources :courses, :only => [:show]
  
  # Events
  match 'events/:id' => 'events#show', :as => :event
  match 'future' => 'events#future', :as => :future_events
  match 'past' => 'events#past', :as => :past_events
  match 'courses' => 'events#courses', :as => :courses
  
  # Blog
  match 'blog' => 'articles#index', :as => :blog
  match 'blog/:id' => 'articles#show', :as => :article
  match '/blog_feed' => 'articles#feed',
        :as => :blog_feed,
        :defaults => { :format => 'atom' }
        
  match '/events_feed' => 'events#feed',
        :as => :events_feed,
        :defaults => { :format => 'atom' }
  
  # Static Pages
  match '/contacts' => 'static_pages#contacts'
  match '/school' => 'static_pages#school'
  match '/services' => 'static_pages#services'

  root :to => 'static_pages#home'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  match '/:id' => 'pages#show', :as => :page

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_filter :set_contacts_text, only: :contacts

  def home
    @main = Event.master_classes.published.main.future.not_filled
    @future = Event.master_classes.published.future.order("date asc")
    if Event.master_classes.published.future.not_filled.count < 3
      @future = @future.limit(3)
    else
      @future = @future.not_filled.limit(3)
    end
    @past = Event.master_classes.published.past.order("date desc").limit(3)
    @courses = Event.courses.published.order("date desc").limit(3)
    @slides = Slide.all
  end

  def contacts
    @event = Event.published.future.order("date asc").first
    @events = Event.published.future.order("date asc").limit(3)
  end

  def shcool
  end

  def services
  end

  def vacancy
    @page = Page.find_by_section('vacancy')
  end

  def set_contacts_text
    if ContactsPage.first
      @text = ContactsPage.first.text
    else
      @text = nil
    end
  end
end

app/views/static_pages/_elements.html.erb
<div class="blocks-main">
  <% events.each do |event| %>
    <div class="block">
      <% unless event.front_images.blank? %>
        <%= link_to image_tag(event.front_images.first.image.url(:thumb)), event %>
      <% end %>
      <h2><%= event.title %></h2>
      <span class="blocks-date">
        <%= event_date_time(event, true) %><%= event.price %> 
        <span class="b-rub">Р</span>
      </span>
      <p><%= event_duration(event) %></p>
      <p><%= event.shorttext %></p>
      <%= link_to "подробнее", event %>
      <% unless event.past? %>
        <%= order_link_normal(event) %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/static_pages/contacts.html.erb
<% @title = "Контакты" %>
<% content_for :head do %>
<script src="http://api-maps.yandex.ru/2.0/?load=package.standard&mode=debug&lang=ru-RU" type="text/javascript"></script>
<script type="text/javascript">
    /* При успешной загрузке API выполняется
       соответствующая функция */
    ymaps.ready(function () {
       var myMap = new ymaps.Map("YMapsID", {
// Центр карты
center: [59.9160,30.3091],
// Коэффициент масштабирования
zoom: 16,
// Тип карты
type: "yandex#map"
}
);
    var myPlacemark = new ymaps.Placemark(
// Координаты метки
[59.9177,30.3081], {
    /* Свойства метки:
       - контент значка метки */
    iconContent: "",
    // - контент балуна метки
    balloonContent: "Красиво подано"
}, {
    /* Опции метки:
       - флаг перетаскивания метки */
    draggable: false,
    /* - показывать значок метки
       при открытии балуна */
    hideIconOnBalloonOpen: true
}
);

// Добавление метки на карту
myMap.geoObjects.add(myPlacemark);


    });
</script>
<% end %>

<div class="content">
  <div class="fotorama-container map">
    <div id="YMapsID" style="height: 750px;"></div>
  </div>
  <div class="container">

    <aside>
      <% unless @event.nil? %>
      <div class="event-info">
        <p>Кстати, у нас есть кое-что:</p>
        <p>
          <span class="strong">
            <% if @event.date %>
            <%= Russian::strftime(@event.date, "%d %B") if @event.date %> —
            <% end %>
            <%= @event.title %>
          </span>
        </p>
        <p>стоимость: <span class="strong"><%= @event.price %> <span class="b-rub">Р</span></span></p>
        <p><%= link_to "Подробнее", @event %></p>
      </div>
      <% end %>
      <%= render 'shared/vk_widget' %>
    </aside>

    <section class="event-main">
      <%= @text.html_safe %>
      <div class="buf"></div>
    </section>

    <div class="buf"></div>
  </div>

  <% unless @events.blank? %>
    <div class="blocks-bottom inner-page">
      <% @events.each do |event| %>
        <div class="block">
          <% unless event.front_images.blank? %>
            <%= link_to image_tag(event.front_images.first.image.url(:thumb)), event %>
          <% end %>
          <h2><%= event.title %></h2>
          <span class="blocks-date">
            <%= event_date_time(event, true) %><%= event.price %>
            <span class="b-rub">Р</span>
          </span>
          <p><%= event_duration(event) %></p>
          <p><%= event.shorttext %></p>
          <%= link_to "подробнее", event %>
          <% unless event.past? %>
            <%= order_link_normal(event) %>
          <% end %>
        </div>
      <% end %>
    </div>
    <% end %>

</div>

app/views/static_pages/home.html.erb
<% content_for :head do %>
<meta name='yandex-verification' content='751d5d2b5ce252fc' />
<% end %>
<div class="content"> 
	<%= render 'shared/slider' %>
  <!-- ПРЕДСТОЯЩИЕ СОБЫТИЯ -->
  <% unless @future.blank? %>
  	<div class="blocks-main">
  		<h1><%= link_to "Предстоящие события", future_events_path %></h1>
  	</div>	
    <%= render 'elements', :events => @future %>
	<% end %>
  <!-- НАШИ КУРСЫ -->
	<% unless @courses.blank? %>
  	<div class="blocks-main">
  		<h1><%= link_to "Наши курсы", courses_path %></h1>
  	</div>	
    <%= render 'elements', :events => @courses %>
	<% end %>
  <!-- ПРОШЕДШИЕ СОБЫТИЯ -->
	<% unless @past.blank? %>
  	<div class="blocks-main">
  		<h1><%= link_to "Прошедшие события", past_events_path %></h1>
  	</div>
    <%= render 'elements', :events => @past %>
	<% end %>	
</div>

app/views/static_pages/school.html.erb
<% @title = "О школе" %>

<div class="content">
  <div class="container" style="margin-top: 200px; margin-bottom: 50px; min-height: 300px;">
	<div class="text-page">
	<h3>Наша школа открыта  для всех, кто хочет научиться готовить не хуже шеф-повара и, приходя в ресторан, смотреть на подаваемые блюда взглядом эксперта, а также для тех, кто лишен тщеславия и просто желает порадовать своих домашних. </h3>
            
    <h1>Кто может стать нашим учеником?</h1>
   
    <p>Каждый, кто неравнодушен к высокой кухне, новым знаниям и умениям, а также все, кто любит нескучно и с пользой проводить свободное время. </p>

    <h1>Чему учим?</h1>

    <p>Каждый месяц мы разрабатываем учебную программу - наше "<a style="color: #249ee7;" href="http://krasivopodano.ru/future">Расписание занятий</a>". Оно строится по принципу "сегодня в ресторане, завтра на уроке". В нашем учебном плане вы всегда найдете самые известные ресторанные блюда, а значит, уже совсем скоро сможете сами их готовить и, конечно же, красиво подавать.</p>

    <h1>В школу нужно ходить каждый день?</h1>

    <p>Вовсе нет. Просто выберите из расписания самый интересный для вас урок и запишитесь на него. </p>

    <h1>Как проходят занятия?</h1>

    <p>Все уроки в "Красиво подано" проходят в форме мастер-классов. Мы приглашаем лучших шеф-поваров, которые нескучно рассказывают, интересно показывают и чутко помогают каждому ученику сделать все на высшем уровне. Каждый из наших гостей во время урока получает все необходимые продукты, посуду, индивидуальное рабочее место с  варочной поверхностью и духовым шкафом. </p>

    <h1>Сколько длится один урок?</h1>

    <p>От 1,5 до 3-х часов - все зависит от количества блюд, которые шеф-повар будет вместе с вами интересно готовить. Однако в Расписании есть и "задачки со звездочкой" - это уроки, которые разбиты на несколько частей и проходят в течение 2 или даже 3 дней. В этом случае вы можете записаться на ту часть занятия курса, которая вам больше всего интересна, или же, как прилежный ученик, посетить все уроки. </p>

    <h1>Сколько человек может находиться в классе во время занятия?</h1>

    <p>У нас есть 12 отдельных полностью оборудованных рабочих мест для учеников. Но вы также можете взять с собой знакомых и друзей, которые  будут наблюдать за ростом вашего кулинарного мастерства. А после - смогут отметить ваши успехи, попробовав приготовленные блюда в нашей уютной гостиной. </p>

    <h1>Никаких конспектов!</h1>

    <p>У нас нет утомительных лекций, теоретических занятий, рассказов о том, как шеф в свое время служил в армии или однажды ездил с друзьями на рыбалку. Хотя, может быть, это наше упущение… Однако мы постарались выстроить программу каждого мастер-класса максимально информативной, доступной и увлекательной. Вы учитесь готовить "здесь и сейчас" - все, что есть у шефа на столе, есть и у вас, вместе с его советами, наставлениями и обаянием вы, повторяя за мастером, готовите блюда высокой кухни.</p>

    <h1>А с детьми к вам можно?</h1>

    <p>Нужно! Даже для самых маленьких у нас есть занятия, которые научат юных кулинаров готовить их любимые блюда. К тому же, кулинарный утренник - один из самых увлекательных способов отметить День рождения. Расскажите нам о своем желании устроить детский праздник в Красиво Подано и <a style="color: #249ee7;" href="http://krasivopodano.ru/future">запишитесь на урок прямо сейчас</a>.</p>

    <h1>Вечеринка в школе!</h1>

    <p>Приходите к нам с друзьями, чтобы интересно и необычно отметить День рождения или любой значимый для вас праздник. В этот день школа будет работать только для вас. Мы подготовим особый мастер-класс для вас и ваших гостей, торжественно украсим гостиную, позовем музыкантов - устроим самую настоящую вечеринку. В такие дни Красиво Подано превращается в небольшой уютный семейный ресторанчик, в котором у вас всегда есть доступ на кухню.</p>

    <h1>Индивидуальные занятия </h1>

    <p>Мы понимаем, что в школу ходить иногда не хочется, хочется загорать и купаться. Именно поэтому мы приготовили выездные мастер-классы. В этот день школа приезжает к вам! Посуда, вся необходимая мебель, продукты, мангалы и печи отправляются туда, где вы их больше всего расположены видеть. Мы даже можем не нагружать вас знаниями, а просто приехать, приготовить, сервировать столы и, конечно, красиво подать ваши любимые блюда. Некоторые называют это "кейтеринг", но мы - индивидуальными занятиями. </p>
    </div>
    </div>
</div>

app/views/static_pages/services.html.erb
<% @title = "Что преподаем" %>

<div class="content">
  <div class="container" style="margin-top: 200px; margin-bottom: 50px; min-height: 300px;">
	<div class="text-page">
		<h1>Кулинарные мастер-классы для взрослых и детей</h1>

		<p>Если есть свободное время - потратьте его с пользой и удовольствием. Просто купите билет на урок и приходите к нам на занятия. Точно так же, как вы это делаете, когда собираетесь в кино.</p>

		<p>Все мастер-классы в нашей школе могут быть длинными или короткими:</p>


		<h3 style="text-transform: uppercase">Короткий мастер-класс</h3>

		<p>Проводятся в один день. Длится от 1.5 до 3 часов в зависимости от 
		количества блюд, которые вам предстоит научиться готовить. </p>

		<h3 style="text-transform: uppercase">Длинный мастер-класс</h3>

		<p>Может проходить в течение 2-х или 3-х дней. 
		Мы разбиваем большой урок на несколько частей. Вы можете купить
		билет на одно из занятий курса или приобрести абонемент  по более
		привлекательной цене.</p>

		<h1>Детские Дни рождения и праздники</h1>

		<p>Школа превращается в домашний ресторанчик. Большая светлая гостиная
		украшается шарами и гирляндами, мы приглашаем аниматоров, готовим
		праздничный торт, разрабатываем специальное меню для наших маленьких
		гостей. Вы также можете заказать праздничный кулинарный мастер-класс -  всегда интересно и весело попробовать приготовить угощение самим.</p>

		<h1>Проведение любых торжественных событий в Школе </h1>

		<p>Дружеские посиделки</br>
		Девичники/Мальчишники</br>
		Дни рождения</br>
		Корпоративные вечеринки</p>

		<p>В этот день наш шеф приготовит особый мастер-класс, на котором каждый из ваших гостей сможет попробовать себя в качестве повара одного из лучших ресторанов. Программа вечера может быть абсолютно любой - просто расскажите нам, как бы вам хотелось красиво отдохнуть, и мы абсолютно все подготовим:</p>

		<p>- трансферы гостей в школу и из школы;</br>
		- фото и видеосъемку вечеринки;</br>
		- кулинарные конкурсы и мастер-классы;</br>
		- разработаем особое меню;</br>
		- пригласим музыкантов и артистов.</p>

		<h1>Выездные мастер-классы</h1>

		<p>Когда отдых уже спланирован, место выбрано, гости приглашены, но хочется сделать вечеринку еще интереснее. Как насчет гастрономического мастер-класса у вас дома или за городом под тенью ветвистых деревьев, на свежем воздухе в окружении добрых друзей, любящих интересно и с пользой проводить свое время? </p>
	<p>Мы привезем все необходимое оборудование, посуду, продукты - все, что требуется для приготовления выбранных вами блюд. Увлекательный кулинарный урок станет отличным сюрпризом для гостей. </p> 

		<h1>Шеф-повар в аренду (или "Шеф повар на час")</h1>

		<p>На тот случай, если вы хотите удивить каждого, кто сядет за ваш праздничный стол в этот вечер. Но здесь есть опасность - лавина вопросов и просьб поделиться рецептом и фирменным секретом может накрыть. Будьте осторожны.</p>

		<h1>Фото-  и видеосъемка кулинарных событий </h1>

		<p>Мастер-класс - это всегда интересно и весело. Это новый опыт, новые знакомства, новое ощущение себя. Будет обидно остаться без ярких воспоминаний.</p>
		<p>Именно поэтому в Красиво Подано есть настоящая профессиональная фотостудия. Работы фуд-стилиста Максима Николаева можно увидеть в меню лучших ресторанов Санкт-Петербурга и Москвы. А фотоотчеты о последних  событиях Школы  - в группе "Контакте".</p>
		<p>Вы  можете заказать у нас специальный фото или видеорепортаж вашего мероприятия в Красиво Подано или вне стен Школы прямо сейчас.</p>

		<h1>Организация трансфера гостей Школы</h1>

		<p>Встретим и с комфортом доставим вас и ваших гостей в Красиво Подано. А после мероприятия так же красиво и бережно развезем по домам.</p>

    </div>
    </div>
</div>

app/views/static_pages/vacancy.html.erb
<% @title = "Вакансии" %>

<div class="content">
  <div class="container blog" style="margin-bottom: 50px">
    <h1><%= @page.title %></h1>
	<div><%= @page.text.html_safe %></div>

  </div>
</div>